### ISSUE TITLE
When a new user joins, they get three welcome messages

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/greetbot#63] opened 2018-04-12 19:40 UTC
When a new user signs up, they'll see the "welcome" message fire thrice.

Some people want to report this as a bug.

**Comment by lpatmo** [comment] 2018-04-15 07:57
I've created a new user and can verify that this happens.

**Comment by stain88** [comment] 2018-04-15 16:13
Is this a new user to codebuddies, or the greetbot slack?
If codebuddies, I can't reproduce. If greetbot, it's probably because we've "duped" the bots for individual testing, so all of them fire.

**Comment by BethanyG** [comment] 2018-04-15 17:41
Confirm that a new user to **_codebuddies.slack.com_** gets (_in my case_) two bot instances and two Welcome messages.  This was after I invited the user via an **email/link** from the Slack interface.  **However** @stain88 used the "self-invite" method (the [get your invite] button on the website) - and only received a single message on joining. 

I removed the second bot configuration for codebuddies.  With one bot, I am only getting one welcome message (unless I click the "how does this app work?" link in the welcome message -- then I get two.

Currently, this deactivates the `/welcome` functionality for the bot (the current configuration doesn't have `/` commands configured.  However, this will be fixed when we deploy the completed `/resources` functionality.

Can someone re-test, and reconfirm?  Thanks!

**Comment by BethanyG** [comment] 2018-04-15 18:22
Tested and confirmed by sending invites to @angelocordon and @stain88.  Since they are now only getting spammed once, I am going to close this as fixed for now.

**Closed as completed by BethanyG** 2018-04-15 18:22 UTC
